name: Hello World Module
description: |
    This is the description for the Hello World module.
identifier: org.smcore.helloworld
version: 1.0
author:
    name: smCore Dev Team
    website: http://smcore.org

namespaces:
    php:      smCore\HelloWorld
    lang:     hello
    template: hello

routes:
    main:
        match: hello
        controller: Main
        method: myMainMethod